site:
  title: 'Local Technical Documentation'
  start_page: documentation::index.adoc

content:
  sources:
    - url: /Users/colmandmarc/Desktop/Anyline Documentation/Antora-Test-Project/antora-local-content-main
      branches: [main]
      start_path: .

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

output:
  clean: true
  dir: ./build/site
